name: "Terraform"

on:
  push:
    branches:
      - main
      - feature/add-makefile
  pull_request:

jobs:
  terraform:
    name: "Unit Tests"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Format
        id: fmt
        run: make fmt
        working-directory: ./how-to-use-this-module
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: make init
        working-directory: ./how-to-use-this-module

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./how-to-use-this-module

      - name: Validação do tfsec
        id: tfsec
        run: |
          docker run --rm -v $PWD:/app -w /app tfsec/tfsec . 
